@startuml architecture

component core {
	package foodie.core
	package foodie.json
}

component Jackson {
}

foodie.json ..> Jackson

component ui {
	package foodie.ui
}

foodie.ui ..> foodie.core
foodie.ui ..> foodie.json

component javafx {
	component fxml {
	}
}

ui ..> javafx
ui ..> fxml

component restapi {
	package foodie.restapi
}

foodie.restapi ..> foodie.core
foodie.restapi ..> foodie.json

component SpringBootApplication {	
}

foodie.restapi ..> SpringBootApplication


@enduml
