@startuml architecture

component core {
	package foodie.core
	package foodie.json
}

component JSON.simple {
}

foodie.json ..> JSON.simple

component ui {
	package foodie.ui
}

foodie.ui ..> foodie.core
foodie.ui ..> foodie.json

component javafx {
	component fxml {
	}
}

ui ..> javafx
ui ..> fxml

component restapi {
	package foodie.restapi
}

foodie.restapi ..> foodie.core
foodie.restapi ..> foodie.json

component spring {
}

restapi ..> spring

component restserver {
	package foodie.restserver
}

foodie.restserver ..> foodie.core
foodie.restserver ..> foodie.restapi

component jersey {
}

component grizzly2 {
}

restserver ..> jersey
restserver ..> grizzly2

@enduml
